spring:
  profiles:
    active: mac

  application:
    name: HiddenBATHAuto

as:
  sms:
    reminder:
      template: |
        [히든바스] 내일({date}) 신청하신 AS에 대한 기사님이 방문하실 예정입니다.
        기사님 성함 : {engineerName}
        기사님 연락처 : {engineerPhone}

server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: native
  servlet:
    session:
      timeout: 43200m
      cookie:
        max-age: 2592000
        name: SID
        http-only: true
        secure: false

kakao:
  base-url: https://dapi.kakao.com
  rest:
    api-key: "0daa583a542a7c7639b42072873d05b9"
  throttle-ms: 120

juso:
  confm-key: "devU01TX0FVVEgyMDI2MDExMDEzMDkyNjExNzQyMDk="
  base-url: https://business.juso.go.kr
  first-sort: location
  throttle-ms: 0
  count-per-page: 10
  timeout-seconds: 5

logging:
  config: classpath:logback-spring.xml