spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://1.234.53.160:3306/hiddenauto_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 'hidden3660!@'
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      maxFileSize: 5000MB
      maxRequestSize: -1

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'admin@hiddenbath.co.kr'
    password: 'hfdpehjnemsxvhre'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  upload:
    path: "${user.home}/Desktop/product/"
    env: mac